CREATE DATABASE chat;

USE chat;

-- MySQL Script generated by MySQL Workbench
-- Thu Apr 16 11:40:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8 ;
USE `chat` ;

-- -----------------------------------------------------
-- Table `chat`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat`.`messages` ;

CREATE TABLE IF NOT EXISTS `chat`.`messages` (
  `idmessages` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `rooms_idrooms` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idmessages`),
  INDEX `fk_messages_rooms_idx` (`rooms_idrooms` ASC) VISIBLE,
  INDEX `fk_messages_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_messages_rooms`
    FOREIGN KEY (`rooms_idrooms`)
    REFERENCES `chat`.`rooms` (`idrooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `chat`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat`.`rooms` ;

CREATE TABLE IF NOT EXISTS `chat`.`rooms` (
  `idrooms` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idrooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat`.`users` ;

CREATE TABLE IF NOT EXISTS `chat`.`users` (
  `idusers` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;

USE `chat` ;

-- -----------------------------------------------------
-- Placeholder table for view `chat`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `chat`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat`.`view1`;
DROP VIEW IF EXISTS `chat`.`view1` ;
USE `chat`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
